version: "3.3"

services:

  dbfruver:
    container_name: ${PROJECT}_dbfruver
    hostname: ${PROJECT}_dbfruver
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - bddata:/var/lib/mysql
      - ./database/dump:/docker-entrypoint-initdb.d
    networks:
      - platform
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  fruver:
    container_name: ${PROJECT}_fruver
    hostname: ${PROJECT}_fruver
    build: ./fruver
    depends_on:
      - dbfruver
    volumes:
      - ./fruver/fruver:/code
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    networks:
      - platform

volumes:
  bddata:

networks:
  platform:
    name: platform